apiVersion: v1
kind: Service
metadata:
  name: cloud-autoscaling-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-autoscaling-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000